"use client";

import { motion } from "framer-motion";
import { 
  ArrowLeft, 
  FileText, 
  Download, 
  Share2, 
  Calendar, 
  Shield, 
  ChevronRight,
  Clock
} from "lucide-react";
import { Button } from "@/components/ui/button";
import type { WorkProfile, SymptomLog } from "@/app/page";

interface DocumentationScreenProps {
  workProfile: WorkProfile | null;
  symptomLogs: SymptomLog[];
  onNext: () => void;
  onBack: () => void;
}

const SYMPTOM_LABELS: Record<string, string> = {
  cough: "Persistent cough",
  shortness: "Shortness of breath",
  wheezing: "Wheezing",
  chest_tight: "Chest tightness",
  dust_react: "Dust/fume reaction",
  rash: "Skin rash",
  itching: "Itching",
  dryness: "Skin dryness",
  burns: "Chemical burns",
  discolor: "Skin discoloration",
  back_pain: "Back pain",
  joint_pain: "Joint pain",
  numbness: "Numbness",
  muscle_weak: "Muscle weakness",
  neck_pain: "Neck/shoulder pain",
};

const SEVERITY_LABELS = ["", "Mild", "Moderate", "Severe", "Very Severe"];

export function DocumentationScreen({
  workProfile,
  symptomLogs,
  onNext,
  onBack,
}: DocumentationScreenProps) {
  const totalLogs = symptomLogs.length;
  const uniqueSymptoms = new Set(symptomLogs.flatMap((log) => log.symptoms)).size;
  const avgSeverity =
    symptomLogs.length > 0
      ? Math.round(
          symptomLogs.reduce((acc, log) => acc + log.severity, 0) / symptomLogs.length
        )
      : 0;

  const handleDownload = () => {
    // Generate a simple text report
    let report = `SEHAT SAATHI - Health Documentation Report\n`;
    report += `=========================================\n\n`;
    report += `Worker: ${workProfile?.name || "Anonymous"}\n`;
    report += `Industry: ${workProfile?.factoryType || "Not specified"}\n`;
    report += `District: ${workProfile?.district || "Not specified"}\n`;
    report += `Years of Work: ${workProfile?.yearsWorking || "Not specified"}\n`;
    report += `Report Generated: ${new Date().toLocaleString("en-IN")}\n\n`;
    report += `HEALTH LOG SUMMARY\n`;
    report += `------------------\n`;
    report += `Total Check-ins: ${totalLogs}\n`;
    report += `Unique Symptoms: ${uniqueSymptoms}\n`;
    report += `Average Severity: ${SEVERITY_LABELS[avgSeverity] || "N/A"}\n\n`;
    report += `DETAILED LOGS\n`;
    report += `-------------\n`;
    
    symptomLogs.forEach((log, index) => {
      report += `\n[${index + 1}] ${new Date(log.date).toLocaleDateString("en-IN")}\n`;
      report += `Symptoms: ${log.symptoms.map(s => SYMPTOM_LABELS[s] || s).join(", ")}\n`;
      report += `Severity: ${SEVERITY_LABELS[log.severity]}\n`;
      if (log.notes) report += `Notes: ${log.notes}\n`;
    });

    report += `\n=========================================\n`;
    report += `This document serves as timestamped proof of occupational health concerns.\n`;
    report += `Generated by SehatSaathi - Worker Health Protection System\n`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `health-record-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    const shareText = `My SehatSaathi Health Record\n\nTotal Check-ins: ${totalLogs}\nSymptoms Tracked: ${uniqueSymptoms}\n\nThis worker-owned health documentation helps detect occupational diseases early.`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: "SehatSaathi Health Record",
          text: shareText,
        });
      } catch {
        // User cancelled sharing
      }
    }
  };

  return (
    <div className="flex min-h-screen flex-col bg-background">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background/95 px-4 py-4 backdrop-blur">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={onBack}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div className="flex-1">
            <h1 className="text-lg font-semibold text-foreground">My Health Record</h1>
            <p className="text-sm text-muted-foreground">Your documented proof</p>
          </div>
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10">
            <FileText className="h-5 w-5 text-primary" />
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-auto px-4 pb-32">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="space-y-6 py-4"
        >
          {/* Profile Card */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl bg-gradient-to-br from-primary to-primary/80 p-6 text-primary-foreground"
          >
            <div className="mb-4 flex items-center gap-3">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-white/20">
                <Shield className="h-6 w-6" />
              </div>
              <div>
                <h2 className="text-xl font-bold">{workProfile?.name || "Worker"}</h2>
                <p className="text-sm text-primary-foreground/80">
                  {workProfile?.factoryType === "plastic"
                    ? "Plastic Manufacturing"
                    : workProfile?.factoryType === "textile"
                    ? "Textile Worker"
                    : "Factory Worker"}{" "}
                  · {workProfile?.district}
                </p>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-4 text-center">
              <div className="rounded-xl bg-white/10 py-3">
                <div className="text-2xl font-bold">{totalLogs}</div>
                <div className="text-xs text-primary-foreground/80">Check-ins</div>
              </div>
              <div className="rounded-xl bg-white/10 py-3">
                <div className="text-2xl font-bold">{uniqueSymptoms}</div>
                <div className="text-xs text-primary-foreground/80">Symptoms</div>
              </div>
              <div className="rounded-xl bg-white/10 py-3">
                <div className="text-2xl font-bold">{workProfile?.yearsWorking || 0}y</div>
                <div className="text-xs text-primary-foreground/80">Experience</div>
              </div>
            </div>
          </motion.div>

          {/* Quick Actions */}
          <div className="grid grid-cols-2 gap-3">
            <motion.button
              whileTap={{ scale: 0.98 }}
              onClick={handleDownload}
              className="flex flex-col items-center gap-2 rounded-xl border border-border bg-card p-4"
            >
              <Download className="h-6 w-6 text-primary" />
              <span className="text-sm font-medium text-card-foreground">Download Report</span>
            </motion.button>
            <motion.button
              whileTap={{ scale: 0.98 }}
              onClick={handleShare}
              className="flex flex-col items-center gap-2 rounded-xl border border-border bg-card p-4"
            >
              <Share2 className="h-6 w-6 text-primary" />
              <span className="text-sm font-medium text-card-foreground">Share Record</span>
            </motion.button>
          </div>

          {/* Timeline */}
          <div>
            <h3 className="mb-4 font-semibold text-foreground">Health Timeline</h3>
            <div className="space-y-3">
              {symptomLogs.length === 0 ? (
                <div className="rounded-xl border border-dashed border-border bg-muted/30 p-6 text-center">
                  <Calendar className="mx-auto mb-2 h-8 w-8 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">
                    Your health check-ins will appear here
                  </p>
                </div>
              ) : (
                symptomLogs.slice().reverse().map((log, index) => (
                  <motion.div
                    key={log.id}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="relative rounded-xl border border-border bg-card p-4"
                  >
                    <div className="mb-2 flex items-center justify-between">
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Clock className="h-4 w-4" />
                        {new Date(log.date).toLocaleDateString("en-IN", {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                        })}
                      </div>
                      <span
                        className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                          log.severity >= 3
                            ? "bg-red-100 text-red-700"
                            : log.severity === 2
                            ? "bg-yellow-100 text-yellow-700"
                            : "bg-green-100 text-green-700"
                        }`}
                      >
                        {SEVERITY_LABELS[log.severity]}
                      </span>
                    </div>
                    <div className="flex flex-wrap gap-1">
                      {log.symptoms.map((symptom) => (
                        <span
                          key={symptom}
                          className="rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground"
                        >
                          {SYMPTOM_LABELS[symptom] || symptom}
                        </span>
                      ))}
                    </div>
                    {log.notes && (
                      <p className="mt-2 text-sm text-foreground/70 italic">
                        &quot;{log.notes}&quot;
                      </p>
                    )}
                  </motion.div>
                ))
              )}
            </div>
          </div>

          {/* Legal Notice */}
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-4">
            <h4 className="mb-2 flex items-center gap-2 font-semibold text-primary">
              <Shield className="h-4 w-4" />
              Legal Protection
            </h4>
            <p className="text-sm text-foreground/80">
              This timestamped health record serves as documented proof of your occupational health journey. 
              It can be used to support claims under the Employees&apos; State Insurance Act and 
              Workmen&apos;s Compensation Act.
            </p>
          </div>
        </motion.div>
      </div>

      {/* Fixed Bottom */}
      <div className="fixed bottom-0 left-0 right-0 border-t border-border bg-background/95 p-4 backdrop-blur">
        <Button
          onClick={onNext}
          size="lg"
          className="w-full gap-2 bg-primary text-primary-foreground hover:bg-primary/90"
        >
          View My Impact
          <ChevronRight className="h-5 w-5" />
        </Button>
      </div>
    </div>
  );
}
